### ISSUE TITLE
Running the neural punctuator on mobile

### ISSUE THREAD

**Issue by rafiuddinkhan** [attilanagy234/neural-punctuator#6]
**Can you please share the pre-trained model?**

What can we do to convert it into tflite or use the pt file on the mobile device?

**Comment by bana513** [comment]
Final models will soon be uploaded to Huggingface directory, from where you can easily convert them into TF models. However, we are not planning to release any lightweight mobile versions of these models.

**Comment by rafiuddinkhan** [comment]
Thanks @bana513
