### ISSUE TITLE
Checking model output

### ISSUE THREAD

**Issue by UsamaI000** [attilanagy234/neural-punctuator#7]
Hi, I wanted to know if you have implemented to check the model output at test time. Because we had aligned labels according to tokens so model output would be according to that. How can we convert them back to original which was before aligning ?

Best Regards

**Comment by bana513** [comment]
Hi, here is how we did the conversion from predictions to text again: [commit](https://github.com/attilanagy234/neural-punctuator/commit/741e00b290cd14c4850cd7fe729e4f4e28c71155)
